### ISSUE TITLE
syntax error: unexpected end of file

### ISSUE THREAD

**Issue by hectorrrrrr** [buczek/eduroam-ca#2]
In den files
```
create_ca.sh
create_server.sh
```
musste ich
`die() { echo "$*" >&2 ; exit 1 }`
mit
`die() { echo "$*" >&2 ; exit 1; }`
ersetzen, sonst bekomme ich den im Titel genannten Fehler

**Comment by buczek** [comment]
Oh, wie peinlich. Danke!

**Comment by hectorrrrrr** [comment]
Überhaupt nicht! Ich bin ja dankbar für die geniale Lösung! Nun kann ich wenigstens mit gutem Gewissen meinen Usern verklickern, dass sie nur einmalig ihr eduroam auf all ihren Geräten neui konfigurieren müssen
