### ISSUE TITLE
eduroamCA.srl: No such file or directory

### ISSUE THREAD

**Issue by hectorrrrrr** [buczek/eduroam-ca#3]
Beim Ausführen von
`create_server.sh`
bekam ich den im Titel genannten Fehler.
Beim zweiten openssl-Befehl musste ich noch -CAcreateserial mit angeben:
```
openssl x509 \
    -in server.certreq.pem.tmp -req \
    -CA eduroamCA.cert.pem -CAkey eduroamCA.key.pem \
    -out server.cert.pem \
    -extfile openssl.ext.tmp \
    -days 825 \
    -CAcreateserial
```
Entsprechend dann noch .gitognore anpassen, so dass das generierte file eduroamCA.srl ignoriert wird

(Beide issues aufgetreten unter ubuntu (16.04.7 und focal 20.04))

**Comment by buczek** [comment]
Hmm, kann ich mit OpenSSL 1.1.1t und OpenSSL 3.0.2 erst mal nicht reproduzieren. Was sagt dein `openssl version` auf einem der Systeme, wo es nicht geht?

**Comment by hectorrrrrr** [comment]
Oh, hübsch. Ubuntu ist ja echt aktuell:
`OpenSSL 1.0.2g  1 Mar 2016`
bzw.
`OpenSSL 1.1.1f  31 Mar 2020`
In den release notes habe ich spontan nichts gefunden diesbezüglich, aber es ist ja gut möglich, dass in der Zwischenzeit diese option default-mässig gesetzt wird.

Unsere eduroam-Server sind auch uralt und müssen im Zuge der CA-Erneuerung eh upgedated werden. Da sehe ich gerade, dass dann auch 
`OpenSSL 3.0.2 15 Mar 2022`
drauf sein wird.

So gesehen kann von mir aus der Issue auch ignoriert werden.

**Comment by buczek** [comment]
Könnt es sein, das ein von der Distro installiertes `openssl.cnf` bei dem zweiten openssl-Kommando in `create_server.sh` zum Zuge kommt und den Filenamen des Serial-Files setzt und damit den File verpflichtend macht? Das zweite openssl-Kommando hat nämlich kein `-config`, was da auch gar nicht zulässig wäre.

Kannst du es vielleicht mal schnell hiermit versuchen:

``` patch
--- a/create_server.sh
+++ b/create_server.sh
@@ -40,7 +40,7 @@ ${crl_url:+crlDistributionPoints = URI:$crl_url}
 
 __EOF__
 
-openssl x509 \
+OPENSSL_CONF=/dev/null openssl x509 \
     -in server.certreq.pem.tmp -req \
     -CA eduroamCA.cert.pem -CAkey eduroamCA.key.pem \
     -out server.cert.pem \
```
Ich bin nicht sicher, dass das überhaupt das Problem ist und ob man das so beheben kann, aber da ich noch mit meiner Ubuntu-Installation kämpfe, kann ich es nicht selber testen und vielleicht ist die Idee ja richtig und der Workaround funktional.

**Comment by buczek** [comment]
Brauchst nicht testen. Kann das Problem jetzt in einer Ubuntu 18.04.2 VM und OpenSSL 1.1.0g nachvollziehen. `OPENSSL_CONF=/dev/null` reicht leider nicht.

**Comment by buczek** [comment]
`/usr/lib/ssl/openssl.cnf` entfernen (wird tatsächlich gelesen) bringt nix.

Ubuntu 18.04.2 LTS OpenSSL 1.1.1  11 Sep 2018 : BAD
Ubuntu 18.04.6 LTS OpenSSL 1.1.1  11 Sep 2018 : BAD
Ubuntu 22.04.2 LTS OpenSSL 3.0.2 15 Mar 2022  : OK

Alles dazwischen installiert erst mal nicht in meiner qemu/kvm VM. Die habe aber auch jedes Jahr ihren Installer neu erfunden. Und für 18.04 findet man die Source-Packages nicht mehr so einfach. Seufz....

**Comment by buczek** [comment]
Das ist vermutlich die Änderung openssl/openssl@55eafed6fb, ab OpenSSL 1.1.1r .

**Comment by buczek** [comment]
Würde deine Lösung übernehmen (#5). Sieht das richtig aus?
